### ISSUE TITLE
Sizing

### ISSUE THREAD

**Issue by Davis050594** [T3kstiil3/SoundTouch-Chrome-Extension#1]
First of all, I love the extension so far. I don't use the windows ST app at all, but I am already using this a lot. I'm not sure if this bug is appearing on your pc, but on mine I'm having some size formatting issues with graphics. 
With certain songs the album art appears to be zoomed in to the upper left. Also, white text is overlapping a white background. I'm also experiencing a lot of delay with volume control. I'm willing to help with whatever I can. 
![chrome bug](https://cloud.githubusercontent.com/assets/19331703/15227248/3fe3abdc-1854-11e6-9d02-a4c60664ee95.PNG)
![chrome extension 2](https://cloud.githubusercontent.com/assets/19331703/15227254/4467a078-1854-11e6-9997-3e8da1f53f17.PNG)

**Comment by AurelienLoyer** [comment]
Hi, Thank you for your message, 
I will try to correct it in the next update.
Aurélien.

**Comment by AurelienLoyer** [comment]
Done.
- Source list will be replace by playlist name :
  ![image](https://cloud.githubusercontent.com/assets/3717296/15648939/f61b20c0-266d-11e6-8241-1275e7bbc4ae.png)
- The covers are displayed correctly now :
  ![image](https://cloud.githubusercontent.com/assets/3717296/15649117/4cc1e71e-266f-11e6-9d21-6f07e865a4d6.png)

Thanks for you feedback ! 👍

**Comment by Davis050594** [comment]
Awesome! By the way, I'm actually an employee at Bose. I've shared this
with a few others and they love it!
Any chance you've got some other cool tools/apps in the works?

Thanks,
Davis
