### ISSUE TITLE
can not connect

### ISSUE THREAD

**Issue by jdplumma** [T3kstiil3/SoundTouch-Chrome-Extension#11]
will not connect to speaker restarted chromebook but will not find speaker

**Comment by aaycart** [comment]
me pasa lo mismo

**Comment by jdplumma** [comment]
I got it to connect by manually setting up the app with the correct ip adderess.
Lo tengo para conectar al configurar manualmente la aplicación con la dirección IP correcta
I hope the translation is close!?
